#!/usr/bin/php
<?php
require("load.php");

$test = count($_SERVER["argv"]) >= 2 && $_SERVER["argv"][1] == "-t";
$db = $test ? "sova_test" : "sova";

$pdo = new PDO("mysql:host=localhost", "root", "taliyota");

echo "Vytvářím databázi...\n";
$pdo->exec("DROP DATABASE IF EXISTS $db");
$pdo->exec("CREATE DATABASE $db");
$pdo->exec("USE $db");

echo "Vytvářím tabulky...\n";
$pdo->exec(file_get_contents(__DIR__."/db.create.sql"));

echo "Naplňuji tabulky...\n";
loadInfile($pdo, __DIR__."/wordlist.txt", "wordlist", ["word"]);
loadInfile($pdo, __DIR__."/texts.txt", "text", ["code", "text"]);
loadInfile($pdo, __DIR__."/settings.txt", "settings", ["name", "value"]);

if (!$test) {
	$pdo->exec("INSERT INTO user VALUES (1, 'admin', '".password_hash("nimda", PASSWORD_BCRYPT)."')");
	$pdo->exec("INSERT INTO user VALUES (2, 'org', '".password_hash("gro", PASSWORD_BCRYPT)."')");
	$pdo->exec(file_get_contents(__DIR__."/db.data.sql"));
}
